name: Deploy to MySiteArea via FTP

on:
  push:
    branches: [deploy]
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /thesoftdev.com/public_html/waseem/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
